### ISSUE TITLE
building b18 files crashes with missing property

### ISSUE THREAD

**Issue by th3tick** [kelsin/18xx#157]
I tried building 1860, but it looks like something is missing:

% yarn b18 1860 JMH01 "Kelsin-JMH"
yarn run v1.19.1
$ node ./bin/b18.js 1860 JMH01 Kelsin-JMH
(node:11118) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at /Users/rifleman/Dropbox/Board Games/18xx/18xx/bin/b18.js:169:28
    at _map (/Users/rifleman/Dropbox/Board Games/18xx/18xx/node_modules/ramda/src/internal/_map.js:6:19)
    at map (/Users/rifleman/Dropbox/Board Games/18xx/18xx/node_modules/ramda/src/map.js:64:14)
    at /Users/rifleman/Dropbox/Board Games/18xx/18xx/node_modules/ramda/src/internal/_dispatchable.js:41:15
    at Object.f2 [as map] (/Users/rifleman/Dropbox/Board Games/18xx/18xx/node_modules/ramda/src/internal/_curry2.js:29:14)
    at /Users/rifleman/Dropbox/Board Games/18xx/18xx/bin/b18.js:167:5
    at Object.<anonymous> (/Users/rifleman/Dropbox/Board Games/18xx/18xx/bin/b18.js:243:3)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
(node:11118) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11118) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Perhaps there is a set of required elements that the 1860 file is missing?

**Comment by kelsin** [comment]
Bug due to the new share/token types that you can use in company definitions. Fixed.
